# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08e6b0fa0b692a09455383ff546808554b3d5fbca8f2d663e94c1ed8399cf1b793ed573bd6d315ad5d343fbd59f63bb4d6edcc205bc94c1114637ecb6f215c6b

test:
  secret_key_base: c50c2df4e6f944cad2aa4470b46fc7e01ed74e482870d91a5bed13b06a2b0ee6d1909dbf91dfab8c94bea58a024a0494366fc553c417e797c13f77fa29c10751

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
